<<<<<<< Updated upstream
# Generated by Django 4.1.13 on 2024-03-09 21:16
=======
# Generated by Django 4.1.13 on 2024-05-14 10:59
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
<<<<<<< Updated upstream
=======
                ('username', models.CharField(default=None, max_length=150)),
>>>>>>> Stashed changes
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='offline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='NetworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=150)),
                ('hostname', models.CharField(default=None, max_length=150)),
                ('operating_system', models.CharField(default=None, max_length=150)),
                ('operating_system_version', models.CharField(default=None, max_length=150)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
>>>>>>> Stashed changes
                ('data', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
        migrations.CreateModel(
            name='CPUInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_count', models.IntegerField()),
                ('cpu_percent', models.FloatField()),
                ('cpu_freq_value', models.FloatField()),
                ('threads', models.IntegerField()),
                ('percent_per_cpu', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
<<<<<<< Updated upstream
=======
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=150)),
                ('executed', models.BooleanField(default=False)),
                ('response', djongo.models.fields.JSONField(default=None)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
>>>>>>> Stashed changes
            ],
        ),
    ]
