# Generated by Django 4.1.13 on 2024-03-09 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='offline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
        migrations.CreateModel(
            name='CPUInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_count', models.IntegerField()),
                ('cpu_percent', models.FloatField()),
                ('cpu_freq_value', models.FloatField()),
                ('threads', models.IntegerField()),
                ('percent_per_cpu', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
    ]
