# Generated by Django 4.1.13 on 2024-05-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuinfo',
            name='hostname',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='system_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='username',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
