# Generated by Django 4.1.13 on 2024-03-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpuinfo',
            options={'managed': False},
        ),
    ]
