# Generated by Django 4.2.7 on 2023-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remotecpuinfo_id_remotecpuinfo_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecpuinfo',
            name='pc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
