# Generated by Django 4.1.13 on 2024-05-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cpuinfo_hostname_cpuinfo_system_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpuinfo',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='username',
        ),
    ]
