# Generated by Django 4.2.7 on 2023-11-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cpuinfo_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteCPUInfo',
            fields=[
                ('remote_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('cpu_count', models.IntegerField()),
                ('cpu_percent', models.FloatField()),
                ('cpu_freq_value', models.FloatField()),
                ('threads', models.IntegerField()),
                ('per_cpu_percent', models.JSONField()),
            ],
        ),
    ]
