# Generated by Django 4.1.13 on 2024-03-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cpuinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpuinfo',
            options={},
        ),
    ]
