# Generated by Django 4.2.7 on 2023-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remotecpuinfo_pc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecpuinfo',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
    ]
