# Generated by Django 5.0.3 on 2024-03-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_apitoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitoken',
            name='user',
        ),
        migrations.AddField(
            model_name='apitoken',
            name='username',
            field=models.CharField(default=None, editable=False, max_length=150, unique=True),
        ),
    ]
