# Generated by Django 4.2.7 on 2023-11-17 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remotecpuinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecpuinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
