# Generated by Django 4.1.13 on 2024-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cpuinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuinfo',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
