# Generated by Django 4.2.7 on 2023-11-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remotecpuinfo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecpuinfo',
            name='status',
            field=models.CharField(choices=[('on', 'Online'), ('off', 'Offline')], default='on', max_length=10),
        ),
    ]
