# Generated by Django 5.0.3 on 2024-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_apitoken_user_apitoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='username',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
