# Generated by Django 4.1.13 on 2024-03-09 18:23

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cpuinfo_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apitoken')),
            ],
        ),
    ]
