# Generated by Django 4.2.7 on 2023-11-17 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remotecpuinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecpuinfo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
