# Generated by Django 4.1.13 on 2024-03-09 18:55

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_networkstats_data_networkstats_download_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkstats',
            name='download',
        ),
        migrations.RemoveField(
            model_name='networkstats',
            name='download_speed',
        ),
        migrations.RemoveField(
            model_name='networkstats',
            name='iface',
        ),
        migrations.RemoveField(
            model_name='networkstats',
            name='total_upload',
        ),
        migrations.RemoveField(
            model_name='networkstats',
            name='upload_speed',
        ),
        migrations.AddField(
            model_name='networkstats',
            name='data',
            field=djongo.models.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
