# Generated by Django 4.2.7 on 2023-11-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_remotecpuinfo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecpuinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
