# Generated by Django 4.2.7 on 2023-11-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_remotecpuinfo_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotecpuinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='remotecpuinfo',
            name='timestamp',
        ),
    ]
